kitty_mod ctrl+shift

# BEGIN_KITTY_THEME
# Gruvbox Material Dark Medium
include current-theme.conf
# END_KITTY_THEME
#
#
# Fonts
font_size 12


# Background
background_opacity 0.85

# sub-Window margin
window_margin_width 5
window_border_width 1

# Tab style
tab_bar_edge top
tab_bar_style fade
tab_activity_symbol *

# Window
hide_window_decorations yes

# Cursor trail
# curstor_trail 200
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 2

# Mapping
map ctrl+shift+m launch --cwd=current --type=window /usr/bin/vi .

# Scrolling
map ctrl+shift+k scroll_line_up
map ctrl+shift+j scroll_line_down
map ctrl+shift+z scroll_to_prompt -1

# Window
map ctrl+shift+k previous_window
map ctrl+shift+j next_window
